# 支持向量机

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.utils import shuffle
features = pd.read_excel('镍基高温合金微观数据集合的副本.xlsx')
features
features = pd.read_excel('镍基高温合金微观数据集合的副本.xlsx')
label1 = np.array(features['基体相体积分数'])
label2 = np.array(features['强化相体积分数'])
label3 = np.array(features['液相温度'])
label4 = np.array(features['固相温度'])
label5 = np.array(features['凝固区间'])
label6 = np.array(features['强化相溶解温度'])
label7 = np.array(features['加工窗口'])
features= features.drop('基体相体积分数', axis = 1)
features= features.drop('强化相体积分数', axis = 1)
features= features.drop('液相温度', axis = 1)
features= features.drop('固相温度', axis = 1)
features= features.drop('凝固区间', axis = 1)
features= features.drop('强化相溶解温度', axis = 1)
features= features.drop('加工窗口', axis = 1)
features

,Ni,Cr,Co,Fe,Al,Ti,Nb,Mo,W,C,B,Zr
0,53.3950,17.74,0.31,18.579,0.53,0.97,5.48,2.97,0.00,0.026,0.0000,0.00
1,52.4000,19.01,0.02,18.837,0.57,1.00,5.07,3.06,0.00,0.030,0.0030,0.00
2,55.4315,18.93,11.00,0.000,1.57,3.13,0.00,9.83,0.00,0.075,0.0035,0.03
3,53.2700,18.60,0.00,17.746,1.20,0.80,5.30,3.00,0.00,0.080,0.0040,0.00
4,51.6890,19.20,0.00,19.301,0.70,1.01,5.05,3.05,0.00,0.000,0.0000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
130,74.0931,20.45,0.00,0.000,0.98,2.87,1.57,0.00,0.00,0.030,0.0069,0.00
131,60.4220,18.95,6.94,0.400,2.06,1.29,0.00,3.96,5.94,0.038,0.0000,0.00
132,60.6080,18.50,6.50,1.000,2.10,1.25,0.00,4.00,6.00,0.040,0.0020,0.00
133,62.6180,12.98,8.00,0.000,3.48,2.55,3.50,3.40,3.40,0.060,0.0120,0.00
134,51.2040,18.77,10.88,4.500,1.52,3.10,0.00,9.87,0.00,0.080,0.0060,0.07

In [2]:
n_samples, n_features = features.shape
features = pd.get_dummies(features)
feature_list = list(features.columns)#获取列名
features = np.array(features)#获取影响因子
from sklearn.preprocessing import MinMaxScaler, StandardScaler
features = MinMaxScaler().fit_transform(features)#将进行归一化处理

In [3]:
from sklearn.model_selection import train_test_split
test_ratio = 0.25#按照五比一划分数据集合；4/5的数据用于训练集合，1/5的数据用于验证集合。
SEED = 26 ### the test/train data is checked on this seed, it has similiar distribution to the whole dataset
train_features1, test_features1, train_labels1, test_labels1 = train_test_split(features, label1,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)
train_features2, test_features2, train_labels2, test_labels2 = train_test_split(features, label2,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)
train_features3, test_features3, train_labels3, test_labels3 = train_test_split(features, label3,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)
train_features4, test_features4, train_labels4, test_labels4 = train_test_split(features, label4,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)
train_features5, test_features5, train_labels5, test_labels5 = train_test_split(features, label5,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)
train_features6, test_features6, train_labels6, test_labels6 = train_test_split(features, label6,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)
train_features7, test_features7, train_labels7, test_labels7 = train_test_split(features, label7,
                                                                            test_size = test_ratio,
                                                                            random_state = SEED)

In [4]:
from sklearn.svm import SVR
Model1 = SVR(kernel='rbf', C=1400, gamma=0.1)
Model2 = SVR(kernel='rbf', C=1400, gamma=0.1)
Model3 = SVR(kernel='rbf', C=1400, gamma=0.1)
Model4 = SVR(kernel='rbf', C=1400, gamma=0.1)
Model5 = SVR(kernel='rbf', C=1400, gamma=0.1)
Model6 = SVR(kernel='rbf', C=1400, gamma=0.1)
Model7 = SVR(kernel='rbf', C=1400, gamma=0.1)

In [5]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
def evaluate(true_labels, pred_labels):
    errors = abs(pred_labels - true_labels)
    MAE = mean_absolute_error(true_labels, pred_labels)
    mape = 100 * np.mean(errors / true_labels)
    r2 = r2_score(true_labels, pred_labels)
    RMSE = mean_squared_error(true_labels, pred_labels,squared=False)
    return mape, MAE, RMSE, r2

In [6]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import LeaveOneOut
from numpy import absolute
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_validate
from sklearn.metrics import mean_squared_error
cv = LeaveOneOut()
Model1.fit(train_features1,train_labels1)
Model2.fit(train_features2,train_labels2)
Model3.fit(train_features3,train_labels3)
Model4.fit(train_features4,train_labels4)
Model5.fit(train_features5,train_labels5)
Model6.fit(train_features6,train_labels6)
Model7.fit(train_features7,train_labels7)


from sklearn.model_selection import cross_val_predict
y_pred1 = cross_val_predict(Model1, features, label1, cv=cv)
y_pred2 = cross_val_predict(Model2, features, label2, cv=cv)
y_pred3 = cross_val_predict(Model3, features, label3, cv=cv)
y_pred4 = cross_val_predict(Model4, features, label4, cv=cv)
y_pred5 = cross_val_predict(Model5, features, label5, cv=cv)
y_pred6 = cross_val_predict(Model6, features, label6, cv=cv)
y_pred7 = cross_val_predict(Model7, features, label7, cv=cv)

model_accuracy1, model_MAE1, model_RMSE1, model_r21 = evaluate(label1, y_pred1)
model_accuracy2, model_MAE2, model_RMSE2, model_r22 = evaluate(label2, y_pred2)
model_accuracy3, model_MAE3, model_RMSE3, model_r23 = evaluate(label3, y_pred3)
model_accuracy4, model_MAE4, model_RMSE4, model_r24 = evaluate(label4, y_pred4)
model_accuracy5, model_MAE5, model_RMSE5, model_r25 = evaluate(label5, y_pred5)
model_accuracy6, model_MAE6, model_RMSE6, model_r26 = evaluate(label6, y_pred6)
model_accuracy7, model_MAE7, model_RMSE7, model_r27 = evaluate(label7, y_pred7)


final_output = pd.DataFrame()
final_output.loc[:,1] = [model_accuracy1, model_MAE1, model_RMSE1, model_r21]
final_output.loc[:,2] = [model_accuracy2, model_MAE2, model_RMSE2, model_r22]
final_output.loc[:,3] = [model_accuracy3, model_MAE3, model_RMSE3, model_r23]
final_output.loc[:,4] = [model_accuracy4, model_MAE4, model_RMSE4, model_r24]
final_output.loc[:,5] = [model_accuracy5, model_MAE5, model_RMSE5, model_r25]
final_output.loc[:,6] = [model_accuracy6, model_MAE6, model_RMSE6, model_r26]
final_output.loc[:,7] = [model_accuracy7, model_MAE7, model_RMSE7, model_r27]



final_output=pd.DataFrame(final_output)
final_output=final_output.T
final_output.columns = ['MAPE', 'MAE', 'RMSE', 'R2']
final_output.index = [ '基体相体积分数','强化相体积分数', ' 液相温度','固相温度',
                      '凝固区间','强化相溶解温度','加工窗口']
final_output.to_excel(r'final_output_LOOCV1_svr_11.xlsx', index = True)

In [7]:
data=pd.read_excel('weiguan的副本3.xlsx')
data=data.drop('合金序号', axis = 1)
data

,Ni,Cr,Co,Fe,Al,Ti,Nb,Mo,W,C,B,Zr
0,53.424,18.688,15.360,3.671,2.080,3.392,0.807,2.578,0.000,0.000,0,0
1,52.622,17.565,11.173,0.000,2.015,4.577,2.657,2.414,6.892,0.085,0,0
2,60.219,18.095,6.346,3.972,1.648,4.813,2.178,0.482,2.194,0.053,0,0

In [8]:
new_data_x_scaled=np.array(data)#获取影响因子
predicted_y1 = Model1.predict(new_data_x_scaled)
predicted_y2 = Model2.predict(new_data_x_scaled)
predicted_y3 = Model3.predict(new_data_x_scaled)
predicted_y4 = Model4.predict(new_data_x_scaled)
predicted_y5 = Model5.predict(new_data_x_scaled)
predicted_y6 = Model6.predict(new_data_x_scaled)
predicted_y7 = Model7.predict(new_data_x_scaled)
result_df = pd.DataFrame({'X': new_data_x_scaled.tolist(), '基体相体积分数': predicted_y1,
                             '强化相体积分数': predicted_y2,'液相温度': predicted_y3,'固相温度': predicted_y4,
                             '凝固区间': predicted_y5,'强化相溶解温度': predicted_y6,'加工窗口': predicted_y7,
                             })#将预测的真实值进行还原
result_df.to_excel('微观性能预测结果_6.xlsx', index=False)#保存到表格